image: m.docker-registry.ir/python:3.8-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update && apt-get install make
  - pip install -r requirements.txt

stages:
  - Test

migrations:
  stage: Test
  script:
  - make test-migrations

pylint:
  stage: Test
  script:
    - make test-pylint
