# Generated by Django 3.2.6 on 2021-08-11 12:51

from django.db import migrations, models
import django.db.models.deletion
import workflows.models.python


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20210809_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.task')),
                ('python_file', models.FileField(upload_to=workflows.models.python.user_python_file_directory_path)),
            ],
            bases=('workflows.task',),
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DockerExecuteTask',
            fields=[
                ('taskexecution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.taskexecution')),
                ('container_id', models.CharField(max_length=255)),
            ],
            bases=('workflows.taskexecution',),
        ),
        migrations.CreateModel(
            name='DockerTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.task')),
                ('docker_image', models.CharField(max_length=255)),
            ],
            bases=('workflows.task',),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.task'),
        ),
    ]
