# Generated by Django 3.2.6 on 2021-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_rename_dockerexecutetask_dockertaskexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failed'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
