# Generated by Django 3.2.6 on 2021-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_auto_20210815_1008'),
        ('workflows', '0006_taskexecution_status'),
    ]

    operations = [
    ]
