# Generated by Django 3.2.6 on 2021-08-15 14:45

import django.core.validators
from django.db import migrations, models
import workflows.models.python


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_merge_20210815_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythontask',
            name='python_file',
            field=models.FileField(upload_to=workflows.models.python.user_python_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
    ]
