# Generated by Django 3.2.6 on 2021-08-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_pythontask_python_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow'),
        ),
    ]
