# Generated by Django 3.2.6 on 2021-08-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('workflows', '0009_alter_task_workflow')
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alert_on_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationsource'),
        ),
    ]
