# Generated by Django 3.2.6 on 2021-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_auto_20210816_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeout',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
