# Generated by Django 3.2.6 on 2021-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_merge_0011_task_accessible_datasets_0011_task_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythontask',
            name='docker_image',
            field=models.CharField(default='python:3.8-alpine', max_length=20),
        ),
    ]
