# Generated by Django 3.2.5 on 2021-08-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_task_task_type'),
        ('workflows', '0011_alter_task_workflow'),
        ('workflows', '0013_pythontask_docker_image'),
    ]

    operations = [
    ]
