# Generated by Django 3.2.6 on 2021-08-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0015_alter_pythontask_docker_image'),
        ('workflows', '0015_auto_20210823_0819'),
    ]

    operations = [
    ]
