# Generated by Django 3.2.6 on 2021-08-24 19:00

from django.db import migrations, models
import django.db.models.deletion
import workflows.models.workflow


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_merge_20210823_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('schedule_interval', models.DurationField(validators=[workflows.models.workflow.validate_schedule_interval])),
                ('next_run_time', models.DateTimeField(blank=True, null=True)),
                ('paused', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='workflows.workflow')),
            ],
        ),
    ]
