# Generated by Django 3.2.6 on 2021-08-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_workflowschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tasks', models.ManyToManyField(related_name='_workflows_taskdependency_parent_tasks_+', to='workflows.TaskDependency')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.task')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
        ),
    ]
