# Generated by Django 3.2.6 on 2021-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_workflowschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowschedule',
            name='paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
