# Generated by Django 3.2.6 on 2021-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_workflowschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='secret_variables',
            field=models.ManyToManyField(blank=True, to='workflows.Secret'),
        ),
    ]
