# Generated by Django 3.2.6 on 2021-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_alter_workflowschedule_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DockerTaskExecution',
        ),
    ]
