# Generated by Django 3.2.6 on 2021-08-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_alter_workflowschedule_paused'),
        ('workflows', '0019_alter_taskdependency_parent_tasks'),
        ('workflows', '0020_alter_task_notification_source'),
    ]

    operations = [
    ]
