# Generated by Django 3.2.6 on 2021-08-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_auto_20210828_1052'),
        ('workflows', '0021_merge_20210825_2034'),
    ]

    operations = [
    ]
