# Generated by Django 3.2.6 on 2021-08-28 08:23

from django.db import migrations, models
import workflows.models.task


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_merge_20210828_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=workflows.models.task.task_execution_log_file_directory_path),
        ),
    ]
