# Generated by Django 3.2.6 on 2021-08-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_merge_20210829_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdependency',
            name='parent_tasks',
            field=models.ManyToManyField(blank=True, to='workflows.TaskDependency'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failed'), ('P', 'Pending')], db_index=True, default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Running'), ('S', 'Success'), ('F', 'Failed'), ('P', 'Pending')], db_index=True, default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependencyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='workflows.taskexecution')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependency_executions', to='workflows.workflowexecution')),
            ],
        ),
    ]
