# Generated by Django 3.2.6 on 2021-08-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_auto_20210829_1043'),
        ('workflows', '0023_taskexecution_log'),
    ]

    operations = [
    ]
