# Generated by Django 3.1.7 on 2021-08-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_auto_20210829_1043'),
        ('workflows', '0023_taskexecution_log'),
    ]

    operations = [
    ]
