# Generated by Django 3.2.6 on 2021-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_merge_20210829_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
