# Generated by Django 3.2.6 on 2021-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_merge_0023_auto_20210829_1043_0023_taskexecution_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='run_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_active_executions_count',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
