# Generated by Django 3.2.6 on 2021-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_merge_20210829_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='active_executions_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_active_executions_count',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
