# Generated by Django 3.2.6 on 2021-08-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_merge_0023_auto_20210829_1043_0023_taskexecution_log'),
        ('workflows', '0025_auto_20210829_1826'),
    ]

    operations = [
    ]
