# Generated by Django 3.2.6 on 2021-08-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_taskexecution_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='timestamps',
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='run_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
