# Generated by Django 3.2.6 on 2021-08-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_merge_20210831_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='active_executions_count',
        ),
    ]
