# Generated by Django 3.2.6 on 2021-08-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_merge_20210831_1139'),
        ('workflows', '0027_remove_workflow_active_executions_count'),
    ]

    operations = [
    ]
