# Generated by Django 3.2.6 on 2021-08-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_auto_20210831_0936'),
        ('workflows', '0028_merge_20210831_1208'),
    ]

    operations = [
    ]
