# Generated by Django 3.2.6 on 2021-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_merge_20210831_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='run_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
