# Generated by Django 3.2.6 on 2021-09-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_alter_task_task_type'),
        ('workflows', '0029_taskexecution_extracted_datasets'),
    ]

    operations = [
    ]
