# Generated by Django 3.2.6 on 2021-09-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_merge_20210831_1330'),
        ('workflows', '0030_merge_20210904_1149'),
    ]

    operations = [
    ]
