# Generated by Django 3.2.6 on 2021-09-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0031_alter_task_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workflow',
        ),
    ]
