# Generated by Django 3.2.6 on 2021-09-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_remove_task_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='run_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
