# Generated by Django 3.2.6 on 2021-09-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0031_merge_20210904_1410'),
        ('workflows', '0032_remove_task_workflow'),
    ]

    operations = [
    ]
