# Generated by Django 3.2.6 on 2021-09-05 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_merge_20210905_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
