# Generated by Django 3.2.6 on 2021-09-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_taskexecution_run_time'),
        ('workflows', '0034_taskexecution_created_at'),
    ]

    operations = [
    ]
