# Generated by Django 3.2.6 on 2021-08-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('container_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('NR', 'Not Running'), ('R', 'Running'), ('E', 'Ended')], default='NR', max_length=3)),
                ('run_counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='session_id',
        ),
        migrations.AddField(
            model_name='notebook',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notebooks.session'),
        ),
    ]
