# Generated by Django 3.2.6 on 2021-08-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20210830_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='notebook',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='notebooks.notebook'),
            preserve_default=False,
        ),
    ]
