# Generated by Django 3.2.6 on 2021-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20210830_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='result',
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('D', 'Done'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
