# Generated by Django 3.2.6 on 2021-09-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_cell_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='result',
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_status',
            field=models.CharField(choices=[('R', 'Running'), ('D', 'Done'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cell',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.notebook'),
        ),
    ]
