# Generated by Django 3.2.6 on 2021-09-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_auto_20210831_1132'),
        ('notebooks', '0003_cell_notebook'),
    ]

    operations = [
    ]
