# Generated by Django 3.2.6 on 2021-09-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_auto_20210904_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='notebook',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='notebooks.notebook'),
        ),
    ]
