# Generated by Django 3.2.6 on 2021-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationsource',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
